# Generated by Django 2.1.3 on 2018-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscriptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.IntegerField(choices=[(1, 'Documento Nacional de Identidad'), (2, 'Cédula de Identidad'), (3, 'Libreta de Enrolamiento'), (4, 'Libreta Cívica'), (5, 'Pasaporte')], default=1)),
                ('num_doc', models.CharField(blank=True, max_length=50, verbose_name='Numero de Documento')),
                ('pais', models.CharField(blank=True, max_length=50, verbose_name='Pais')),
                ('provincia', models.CharField(blank=True, max_length=50, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=50, verbose_name='Localidad')),
                ('domicilio', models.CharField(blank=True, max_length=50, verbose_name='Domicilio Particular')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('profesion', models.CharField(blank=True, max_length=50, verbose_name='Profesion')),
                ('ocupacion', models.CharField(blank=True, max_length=50, verbose_name='Ocupacion')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=50, verbose_name='Lugar de Trabajo')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Cargo/Funcion')),
                ('direccion_laboral', models.CharField(blank=True, max_length=50, verbose_name='Direccion Laboral')),
                ('email_laboral', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('telefono_laboral', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Laboral')),
                ('categoria', models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'ADHERENTE'), (3, 'ESTUDIANTE')], default=1)),
            ],
        ),
    ]
