# Generated by Django 2.1.3 on 2018-12-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptos',
            name='apellido',
            field=models.CharField(default='Testing', max_length=50, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscriptos',
            name='nombres',
            field=models.CharField(default='default', max_length=50, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo/Funcion'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='direccion_laboral',
            field=models.CharField(max_length=50, verbose_name='Direccion Laboral'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='domicilio',
            field=models.CharField(max_length=50, verbose_name='Domicilio Particular'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='email',
            field=models.EmailField(default='default', max_length=254, verbose_name='Correo Electronico Personal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='localidad',
            field=models.CharField(max_length=50, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='lugar_trabajo',
            field=models.CharField(max_length=50, verbose_name='Lugar de Trabajo'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='num_doc',
            field=models.CharField(max_length=50, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='ocupacion',
            field=models.CharField(max_length=50, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='profesion',
            field=models.CharField(max_length=50, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
