# Generated by Django 2.1.3 on 2018-12-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_auto_20181227_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptos',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptos',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
