# Generated by Django 2.1.3 on 2018-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_credenciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
