# Generated by Django 2.1.3 on 2018-12-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_credenciales_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credenciales',
        ),
    ]
