# Generated by Django 2.1.3 on 2019-01-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_delete_credenciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico Personal')),
                ('valido', models.BooleanField(default=False)),
            ],
        ),
    ]
