# Generated by Django 2.1.3 on 2019-01-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_mails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='email',
        ),
        migrations.AddField(
            model_name='mails',
            name='email_laboral',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
    ]
