# Generated by Django 2.1.3 on 2019-01-03 05:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_auto_20190103_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('destinatarios', models.IntegerField(choices=[(0, 'Usuarios Registrados'), (1, 'Inscriptos'), (2, 'Correos Validados'), (3, 'Correos Sin Validar')], default=0)),
                ('programar', models.DateTimeField()),
                ('descripcion', tinymce.models.HTMLField()),
                ('terminado', models.BooleanField(default=False)),
            ],
        ),
    ]
