# Generated by Django 2.1.3 on 2019-01-03 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='destinatarios',
            field=models.IntegerField(choices=[(0, 'Usuarios Registrados'), (1, 'Inscriptos'), (2, 'Correos Validados'), (3, 'Correos Sin Validar > Masivo')], default=0),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='programar',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
