# Generated by Django 2.1.3 on 2019-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0011_auto_20190103_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='descripcion',
            new_name='cuerpo',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='titulo',
            field=models.CharField(default='testing', max_length=50, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
