# Generated by Django 2.1.3 on 2019-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0012_auto_20190103_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='cantidad',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='destinatarios',
            field=models.IntegerField(choices=[(0, 'Solo a Mi > Prueba'), (1, 'Usuarios Registrados'), (2, 'Inscriptos'), (3, 'Correos Validados'), (4, 'Correos Sin Validar > Masivo')], default=0),
        ),
    ]
