# Generated by Django 2.1.3 on 2019-01-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0014_mensajes_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='terminado',
            new_name='enviado',
        ),
    ]
