# Generated by Django 2.1.3 on 2019-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0015_auto_20190103_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='progress_url',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
