# Generated by Django 2.1.3 on 2019-01-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0017_progress_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='progress_url',
        ),
    ]
