# Generated by Django 2.1.3 on 2019-03-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0018_remove_mensajes_progress_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_links',
            name='mensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Progress', to='inscripciones.Mensajes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='cantidad',
            field=models.IntegerField(default=100, verbose_name='Batchs'),
        ),
    ]
