# Generated by Django 2.1.3 on 2019-03-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0020_auto_20190321_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='progress_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.Progress_Links'),
        ),
    ]
