# Generated by Django 2.1.3 on 2019-03-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0022_auto_20190321_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='progress_url',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inscripciones.Progress_Links'),
        ),
    ]
