# Generated by Django 2.1.3 on 2019-04-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0025_auto_20190321_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='progress_url',
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='cantidad',
            field=models.IntegerField(default=100),
        ),
    ]
